[package]
name = "wwm"
version = "0.1.0"
authors = ["timun"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winapi = { version = "0.3", features = ["winuser", "errhandlingapi"] }
chrono = "0.4"
lazy_static = "1.4.0"
num-traits = "0.2"
num-derive = "0.3"
dirs = "2.0"
yaml-rust = "0.4.4"